services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hospital_db
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital_password
    volumes:
      - db_data:/var/lib/mysql

  hospital:
    build: .
    container_name: hospital
    ports:
      - "8090:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital_db
    depends_on:
      - mysql
volumes:
  db_data: