name: CI pour le Backend (Spring Boot)

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurer JDK (Java 21 LTS)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Distribution Temurin (Adoptium)
          java-version: '21'       # Version LTS (peut-être '21' si vous préférez)

      # 3. Installer les dépendances avec Maven (sans exécuter les tests)
      - name: Install dependencies (Maven)
        run: mvn install -DskipTests=true

      # 4. Exécuter les tests unitaires
      - name: Run tests
        run: mvn test

      # 5. Construire le jar (artefact)
      - name: Build backend
        run: mvn clean package -DskipTests=true

      # 6. Publier l'artefact (optionnel)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: target/*.jar
